# Wazuh - Filebeat configuration file
# embracingearth.space
# For local docker-compose: uses service name 'wazuh-indexer'
# For production (Fly.io): uses 'localhost' since all services run in same container
# CRITICAL: On Fly.io, Manager/Indexer/Dashboard run in single container via supervisord
# So Filebeat must connect to localhost, not a separate service hostname
output.elasticsearch:
  # Use localhost for Fly.io single-container deployment
  # For local docker-compose, override this with environment variable or separate config
  hosts: ["https://localhost:9200"]
  protocol: https
  username: "admin"
  password: "${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-admin}"
  ssl.verification_mode: none
  ssl.certificate_authorities: ["/etc/wazuh-indexer/certs/root-ca.pem"]
  ssl.certificate: "/etc/wazuh-indexer/certs/wazuh-indexer.pem"
  ssl.key: "/etc/wazuh-indexer/certs/wazuh-indexer-key.pem"

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.enabled: false

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

logging.level: info
