# Wazuh - Filebeat configuration file
output.elasticsearch:
  hosts: ["https://localhost:9200"]
  protocol: https
  username: "admin"
  password: "admin"
  ssl.verification_mode: none
  ssl.certificate_authorities: ["/etc/wazuh-indexer/certs/root-ca.pem"]
  ssl.certificate: "/etc/wazuh-indexer/certs/wazuh-indexer.pem"
  ssl.key: "/etc/wazuh-indexer/certs/wazuh-indexer-key.pem"

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.enabled: false

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

logging.level: info
