# Staging configuration for AI2 platform
app = "ai2-staging"
primary_region = "iad"

# Inherits most config from fly.toml
[build]
  dockerfile = "ai2-core-app/Dockerfile"
  build_args = {
    NODE_ENV = "staging"
  }

[env]
  NODE_ENV = "staging"
  LOG_LEVEL = "debug"
  ENABLE_PROFILING = "true"
  # Disable cluster mode - Fly.io handles horizontal scaling
  CLUSTER_MODE = "false"
  # embracingearth.space branding
  BRAND_URL = "https://embracingearth.space"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.http_checks]]
    interval = "300s"     # Cost-optimized: 5 minutes (was 30s)
    timeout = "10s"       # Increased timeout for stability
    grace_period = "30s"  # More grace time
    method = "get"
    path = "/health"

[[vm]]
  memory = "256mb"       # Already optimized
  cpu_kind = "shared"    # Use shared CPU for cost savings
  cpus = 1 