# PR Preview configuration for AI2 platform
primary_region = "iad"

[build]
  dockerfile = "ai2-core-app/Dockerfile"
  build_args = {
    NODE_ENV = "development"
  }

[env]
  NODE_ENV = "preview"
  LOG_LEVEL = "debug"
  # Disable cluster mode - Fly.io handles horizontal scaling
  CLUSTER_MODE = "false"
  # embracingearth.space branding
  BRAND_URL = "https://embracingearth.space"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  
  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.http_checks]]
    interval = "600s"     # Cost-optimized: 10 minutes for preview (was 60s)
    timeout = "15s"       # Increased timeout for preview stability
    grace_period = "60s"  # More grace time for preview
    method = "get"
    path = "/health"

[[vm]]
  memory = "256mb"       # Already optimized for preview
  cpu_kind = "shared"    # Use shared CPU for cost savings
  cpus = 1 