# Main production configuration for AI2 platform
app = "ai2-production"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "ai2-core-app/Dockerfile"
  build_args = { NODE_ENV = "production" }

[env]
  NODE_ENV = "production"
  PORT = "8080"
  # Disable cluster mode - Fly.io handles horizontal scaling
  CLUSTER_MODE = "false"
  # embracingearth.space branding
  BRAND_URL = "https://embracingearth.space"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "300s"     # Cost-optimized: 5 minutes (was 15s)
    timeout = "10s"       # Increased timeout for stability
    grace_period = "30s"  # More grace time
    restart_limit = 0

  [[services.http_checks]]
    interval = "300s"     # Cost-optimized: 5 minutes (was 10s)
    timeout = "10s"       # Increased timeout for stability
    grace_period = "30s"  # More grace time
    method = "get"
    path = "/health"
    protocol = "http"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"

[mounts]
  source = "ai2_data"
  destination = "/data"

[processes]
  app = "node dist/server.js"
  worker = "node dist/worker.js"

[[vm]]
  memory = "256mb"      # Cost-optimized for low traffic (was 512mb)
  cpu_kind = "shared"   # Use shared CPU for cost savings
  cpus = 1

[metrics]
  port = 9091
  path = "/metrics" 