#!/usr/bin/with-contenv sh
# Verify Indexer can start and fix any issues
# This script runs after data directories are set up but before supervisord starts
# embracingearth.space

set +e # Don't exit on error

echo "🔧 Verifying Indexer startup prerequisites..."

# 1. Verify data directory exists and has correct permissions
INDEXER_DATA="/var/ossec/data/wazuh-indexer-data"
if [ ! -d "$INDEXER_DATA" ]; then
    echo "  Creating Indexer data directory..."
    mkdir -p "$INDEXER_DATA"
    chown -R wazuh-indexer:wazuh-indexer "$INDEXER_DATA" 2>/dev/null || true
    chmod -R 775 "$INDEXER_DATA" 2>/dev/null || true
fi

# 2. Verify temp directory exists
TEMP_DIR="/tmp/wazuh-indexer-tmp"
if [ ! -d "$TEMP_DIR" ]; then
    echo "  Creating Indexer temp directory..."
    mkdir -p "$TEMP_DIR"
    chown -R wazuh-indexer:wazuh-indexer "$TEMP_DIR" 2>/dev/null || true
    chmod -R 777 "$TEMP_DIR" 2>/dev/null || true
fi

# 3. Verify certificates exist
if [ ! -f "/etc/wazuh-indexer/certs/wazuh-indexer.pem" ]; then
    echo "  ⚠️ Indexer certificates not found - will be generated by init script"
fi

# 4. Verify config file exists
if [ ! -f "/etc/wazuh-indexer/opensearch.yml" ]; then
    echo "  ❌ ERROR: Indexer config file not found!"
    exit 1
fi

# 5. Verify binary exists
if [ ! -f "/usr/share/wazuh-indexer/bin/opensearch" ]; then
    echo "  ❌ ERROR: Indexer binary not found!"
    exit 1
fi

# 6. Verify parent directory permissions
chmod 755 /var/ossec/data 2>/dev/null || true
chmod o+x /var/ossec/data 2>/dev/null || true

# 7. Final permission fix on data directory
chown -R wazuh-indexer:wazuh-indexer "$INDEXER_DATA" 2>/dev/null || true
chmod -R 775 "$INDEXER_DATA" 2>/dev/null || true

echo "✅ Indexer startup prerequisites verified"

