# Cloudflare WAF Custom Rules for AI2 Platform
rules:
  # Block common attack patterns
  - name: "Block SQL Injection"
    expression: |
      (http.request.uri.query contains "union" and http.request.uri.query contains "select") or
      (http.request.uri.query contains "'; drop table") or
      (http.request.body contains "'; drop table")
    action: block
    
  # Rate limit AI endpoints
  - name: "AI Endpoint Rate Limit"
    expression: |
      (http.request.uri.path contains "/api/ai") or
      (http.request.uri.path contains "/api/categorize")
    action: challenge
    ratelimit:
      threshold: 10
      period: 60
      
  # Block suspicious user agents
  - name: "Block Bad Bots"
    expression: |
      (http.user_agent contains "scrapy") or
      (http.user_agent contains "wget") or
      (http.user_agent contains "curl" and not ip.src in {$ALLOWED_IPS})
    action: block
    
  # Protect admin endpoints
  - name: "Admin Access Control"
    expression: |
      http.request.uri.path contains "/admin" and
      not ip.src in {$ADMIN_IPS}
    action: challenge 